name: "CI/CD Pipeline" 
on:
  push:
    branches-ignore:
      - josh32-patch-1
      - l10n_develop
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'monitoring/grafana-dashboard.json'
      - 'screenshots/**'
    tags-ignore:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'data/static/i18n/*.json'
      - 'frontend/src/assets/i18n/*.json'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Snyk GitHub Action"
        uses: snyk/actions/setup@master
      - name: "Check out Git repository"
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
      - name: "Use Node.js 14"
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e #v1: v2.x available
        with:
          node-version: 14
      - name: "Install CLI tools"
        run: npm install -g @angular/cli
      - name: "Install application"
        run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts
      - name: "Lint source code"
        run: npm run lint
      - name: "Lint customization configs"
        run: |
          npm run lint:config -- -f ./config/7ms.yml
          npm run lint:config -- -f ./config/addo.yml
          npm run lint:config -- -f ./config/bodgeit.yml
          npm run lint:config -- -f ./config/ctf.yml
          npm run lint:config -- -f ./config/default.yml
          npm run lint:config -- -f ./config/fbctf.yml
          npm run lint:config -- -f ./config/juicebox.yml
          npm run lint:config -- -f ./config/mozilla.yml
          npm run lint:config -- -f ./config/oss.yml
          npm run lint:config -- -f ./config/quiet.yml
          npm run lint:config -- -f ./config/tutorial.yml
          npm run lint:config -- -f ./config/unsafe.yml
      - name: "Snyk library issue test"
        run: snyk test --org=securianteam2-org --all-projects --reachable || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk library issues to snyk.io"
        run: snyk monitor --org=securianteam2-org --all-projects --reachable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk code scan test"
        run: snyk code test --org=securianteam2-org || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk container scan"
        run: "snyk container test Dockerfile --org=securianteam2-org --file=Dockerfile || true"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
